# Generated by Django 5.1.7 on 2025-03-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('consultation_type', models.CharField(choices=[('video', 'video'), ('call', 'call')], max_length=255)),
                ('service_intrest', models.CharField(choices=[('strength', 'strength'), ('weight_loss', 'weight_loss'), ('custom diet', 'custom diet'), ('online coaching', 'online coaching'), ('not sure', 'not sure')], max_length=255)),
                ('pacakage_intrest', models.CharField(choices=[('basic', 'basic'), ('premium', 'premium'), ('vip', 'vip'), ('not sure', 'not sure')], max_length=255)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
